export default [
    {
      id: 1,
      roomName: "The best pattaya floor 16 sea view1",
      place: "The best pattaya",
      price : "10000 baht per month",
      status : 1,
    },
    {
      id: 2,
      roomName: "The best pattaya floor 16 sea view2",
      place: "The best pattaya",
      price : "1,000,000 baht",
      status : 1,
    },
    {
      id: 3,
      roomName: "The best pattaya floor 16 sea view3",
      place: "The best pattaya",
      price : "10000 baht per month",
      status : 0,
    },
    {
      id: 4,
      roomName: "The best pattaya floor 16 sea view4",
      place: "The best pattaya",
      price : "1,000,000 baht",
      status : 1,
    },
    {
      id: 5,
      roomName: "The best pattaya floor 16 sea view5",
      place: "The best pattaya",
      price : "10000 baht per month",
      status : 0,
    },
    {
      id: 6,
      roomName: "The best pattaya floor 16 sea view6",
      place: "The best pattaya",
      price : "1,000,000 baht",
      status : 1,
    },
    {
      id: 7,
      roomName: "The best pattaya floor 16 sea view7",
      place: "The best pattaya",
      price : "10000 baht per month",
      status : 0,
    },
    {
      id: 8,
      roomName: "The best pattaya floor 16 sea view8",
      place: "The best pattaya",
      price : "1,000,000 baht",
      status : 1,
    },
    {
      id: 9,
      roomName: "The best pattaya floor 16 sea view9",
      place: "The best pattaya",
      price : "10000 baht per month",
      status : 0,
    },
    {
      id: 10,
      roomName: "The best pattaya floor 16 sea view10",
      place: "The best pattaya",
      price : "1,000,000 baht",
      status : 1,
    },
    {
      id: 11,
      roomName: "The best pattaya floor 16 sea view10",
      place: "The best pattaya",
      price : "1,000,000 baht",
      status : 1,
    },
    {
      id: 12,
      roomName: "The best pattaya floor 16 sea view10",
      place: "The best pattaya",
      price : "1,000,000 baht",
      status : 1,
    },
    {
      id: 13,
      roomName: "The best pattaya floor 16 sea view10",
      place: "The best pattaya",
      price : "1,000,000 baht",
      status : 1,
    },
    {
      id: 14,
      roomName: "The best pattaya floor 16 sea view10",
      place: "The best pattaya",
      price : "1,000,000 baht",
      status : 1,
    },
    {
      id: 15,
      roomName: "The best pattaya floor 16 sea view10",
      place: "The best pattaya",
      price : "1,000,000 baht",
      status : 1,
    },
    {
      id: 16,
      roomName: "The best pattaya floor 16 sea view10",
      place: "The best pattaya",
      price : "1,000,000 baht",
      status : null,
    },
    {
      id: 17,
      roomName: "The best pattaya floor 16 sea view10",
      place: "The best pattaya",
      price : "1,000,000 baht",
      status : null,
    },
    {
      id: 18,
      roomName: "The best pattaya floor 16 sea view10",
      place: "The best pattaya",
      price : "1,000,000 baht",
      status : null,
    },
    {
      id: 19,
      roomName: "",
      place: "",
      price : "",
      status : null,
    },
    {
      id: 20,
      roomName: "",
      place: "",
      price : "",
      status : null,
    }
  ];